
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a84e8ad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "========================================\n",
      "   Welcome to GradeBook Analyzer!\n",
      "========================================\n",
      "\n",
      "--- Statistics ---\n",
      "Average Marks: 70.50\n",
      "Median Marks: 69.00\n",
      "Highest: vikash (88)\n",
      "Lowest: tyagi (56)\n",
      "\n",
      "--- Grade Summary ---\n",
      "Grade A: 0 student(s)\n",
      "Grade B: 1 student(s)\n",
      "Grade C: 1 student(s)\n",
      "Grade D: 1 student(s)\n",
      "Grade F: 1 student(s)\n",
      "\n",
      "--- Pass/Fail Summary ---\n",
      "Passed (4): ['nikhlesh', 'tyagi', 'vikash', 'anubhav']\n",
      "Failed (0): []\n",
      "\n",
      "--- Final Results ---\n",
      "Name        Marks     Grade\n",
      "------------------------------\n",
      "nikhlesh     78        C\n",
      "tyagi      56        F\n",
      "vikash     88        B\n",
      "anubhav     60        D\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "invalid literal for int() with base 10: ''",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 92\u001b[0m\n\u001b[0;32m     89\u001b[0m             \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mThank you for using GradeBook Analyzer!\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     90\u001b[0m             \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[1;32m---> 92\u001b[0m main()\n",
      "Cell \u001b[1;32mIn[1], line 53\u001b[0m, in \u001b[0;36mmain\u001b[1;34m()\u001b[0m\n\u001b[0;32m     51\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[0;32m     52\u001b[0m     marks \u001b[38;5;241m=\u001b[39m {}\n\u001b[1;32m---> 53\u001b[0m     n \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mint\u001b[39m(\u001b[38;5;28minput\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mEnter number of students: \u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[0;32m     54\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m i \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(n):\n\u001b[0;32m     55\u001b[0m         name \u001b[38;5;241m=\u001b[39m \u001b[38;5;28minput\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mEnter name of student \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mi\u001b[38;5;241m+\u001b[39m\u001b[38;5;241m1\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: \u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[1;31mValueError\u001b[0m: invalid literal for int() with base 10: ''"
     ]
    }
   ],
   "source": [
    "# gradebook.py\n",
    "# Author: nihklesh rohilla \n",
    "# Date: November 2025\n",
    "# Title: GradeBook Analyzer\n",
    "#Roll no:2501730406\n",
    "\n",
    "print(\"========================================\")\n",
    "print(\"   Welcome to GradeBook Analyzer!\")\n",
    "print(\"========================================\")\n",
    "\n",
    "def calculate_average(marks_dict):\n",
    "    return sum(marks_dict.values()) / len(marks_dict)\n",
    "\n",
    "def calculate_median(marks_dict):\n",
    "    marks = sorted(marks_dict.values())\n",
    "    n = len(marks)\n",
    "    if n % 2 == 0:\n",
    "        return (marks[n//2 - 1] + marks[n//2]) / 2\n",
    "    else:\n",
    "        return marks[n//2]\n",
    "\n",
    "def find_max_score(marks_dict):\n",
    "    max_name = max(marks_dict, key=marks_dict.get)\n",
    "    return max_name, marks_dict[max_name]\n",
    "\n",
    "def find_min_score(marks_dict):\n",
    "    min_name = min(marks_dict, key=marks_dict.get)\n",
    "    return min_name, marks_dict[min_name]\n",
    "\n",
    "def assign_grades(marks_dict):\n",
    "    grades = {}\n",
    "    for name, mark in marks_dict.items():\n",
    "        if mark >= 90:\n",
    "            grades[name] = \"A\"\n",
    "        elif mark >= 80:\n",
    "            grades[name] = \"B\"\n",
    "        elif mark >= 70:\n",
    "            grades[name] = \"C\"\n",
    "        elif mark >= 60:\n",
    "            grades[name] = \"D\"\n",
    "        else:\n",
    "            grades[name] = \"F\"\n",
    "    return grades\n",
    "\n",
    "def grade_summary(grades_dict):\n",
    "    summary = {\"A\":0, \"B\":0, \"C\":0, \"D\":0, \"F\":0}\n",
    "    for g in grades_dict.values():\n",
    "        summary[g] += 1\n",
    "    return summary\n",
    "\n",
    "def main():\n",
    "    while True:\n",
    "        marks = {}\n",
    "        n = int(input(\"\\nEnter number of students: \"))\n",
    "        for i in range(n):\n",
    "            name = input(f\"Enter name of student {i+1}: \")\n",
    "            mark = int(input(f\"Enter marks of {name}: \"))\n",
    "            marks[name] = mark\n",
    "\n",
    "        print(\"\\n--- Statistics ---\")\n",
    "        print(f\"Average Marks: {calculate_average(marks):.2f}\")\n",
    "        print(f\"Median Marks: {calculate_median(marks):.2f}\")\n",
    "        max_name, max_score = find_max_score(marks)\n",
    "        min_name, min_score = find_min_score(marks)\n",
    "        print(f\"Highest: {max_name} ({max_score})\")\n",
    "        print(f\"Lowest: {min_name} ({min_score})\")\n",
    "\n",
    "        grades = assign_grades(marks)\n",
    "        summary = grade_summary(grades)\n",
    "\n",
    "        print(\"\\n--- Grade Summary ---\")\n",
    "        for grade, count in summary.items():\n",
    "            print(f\"Grade {grade}: {count} student(s)\")\n",
    "\n",
    "        passed_students = [n for n, m in marks.items() if m >= 40]\n",
    "        failed_students = [n for n, m in marks.items() if m < 40]\n",
    "\n",
    "        print(\"\\n--- Pass/Fail Summary ---\")\n",
    "        print(f\"Passed ({len(passed_students)}): {passed_students}\")\n",
    "        print(f\"Failed ({len(failed_students)}): {failed_students}\")\n",
    "\n",
    "        print(\"\\n--- Final Results ---\")\n",
    "        print(f\"{'Name':<12}{'Marks':<10}{'Grade'}\")\n",
    "        print(\"-\" * 30)\n",
    "        for name in marks:\n",
    "            print(f\"{name:<12}{marks[name]:<10}{grades[name]}\")\n",
    "\n",
    "        choice = input(\"\\nDo you want to analyze again? (yes/no): \").lower()\n",
    "        if choice != 'yes':\n",
    "            print(\"\\nThank you for using GradeBook Analyzer!\")\n",
    "            break\n",
    "\n",
    "main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
